name: digiguru
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  supabase_flutter: ^2.12.2
  cupertino_icons: ^1.0.0
  # http request
  http: ^1.6.0
  # async package to add additional Cancellable operations
  async: ^2.4.1
  # get it
  get_it: ^8.3.0
  # provider
  provider: ^6.1.5+1
  # Stacked Arch
  stacked: ^3.5.0
  stacked_services: ^1.6.0  
  #image_picker: ^1.2.1
  cached_network_image: ^3.4.1
  #xml: ^4.2.0
  #file_picker: ^11.0.2
  filesize: ^2.0.1
  # general purpose media Utils
  #media_utils: ^1.1.1
  video_player: ^2.11.1
  #flutter_uploader: ^3.0.0-beta.4
  #downloading files
  flutter_downloader: ^1.12.0
  file_selector: ^1.1.0
  #path_provider: ^2.1.5
  permission_handler: ^12.0.1
  #video compression
  #light_compressor: ^2.2.0
  video_compress: ^3.1.4
  #video player
  better_native_video_player: ^0.4.11
  #better_player: ^0.0.61
  # for non video doc thumbnail
  #thumbnailer: ^1.1.0
  #video_thumbnail: ^0.2.5+1
  #transparent_image: ^1.0.0
  shared_preferences: ^2.5.5
  #flutter_local_notifications: ^21.0.0

  #firebase_core: ^3.15.2
  #firebase_storage: ^12.4.10
  #firebase_auth: ^5.7.0
  #firebase_in_app_messaging: ^0.3.0+1
  #firebase_remote_config: ^5.5.0
  #firebase_messaging: ^15.2.10
  #firebase_analytics: ^11.6.0
  #cloud_firestore: ^5.6.12
  #firebase_dynamic_links: ^6.1.10

  form_field_validator: ^1.0.1
  convex_bottom_bar: ^3.2.0
  #intl_phone_number_input: ^0.6.0
  #flutter_facebook_auth: ^2.0.2+1
  google_sign_in: ^7.2.0
  #Pdf Viewer
  advanced_pdf_viewer: ^0.13.1
  #advance_pdf_viewer: ^2.0.1
  # numberinput
  flutter_spinbox: ^0.13.1
  #getting deviceinfo
  #device_info_plus: ^12.4.0
  #phone number
  intl_phone_field: ^3.2.0
  #check network connectivity
  connectivity_plus: ^7.1.0
  #widget libraries
  getwidget: ^7.0.0
  expandable: ^5.0.1
  #icon pack
  flutter_vector_icons: ^2.0.0
  auto_size_text: ^3.0.0
  #request user permission on device  this has dependency issue
  #permission_handler: ^6.0.1+1
  #logging
  #logger: ^0.9.4
  #localization  
  intl: ^0.20.2
  #app purchase
  in_app_purchase: ^3.2.3
  #flutter_inapp_purchase: ^8.2.8
  #youtube
  youtube_player_flutter: ^9.1.3
  page_transition: ^2.2.1
  flutter_secure_storage: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/title.png
    - assets/images/icon_large.png
    - assets/images/background.png
    - assets/images/video_icon.png
    - assets/images/pdf_icon.png
    - assets/images/blank_profile.png
    - assets/config/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
